name: Terraform Variable Cleanup

on:
  workflow_call:
  pull_request:


jobs:
  tf-vars-cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Terraform Cleaner
        run: |
          VERSION="${{ github.event.inputs.version }}"
          wget https://github.com/sylwit/terraform-cleaner/releases/download/v${{ github.event.inputs.version || '0.0.4' }}/terraform-cleaner_${{ github.event.inputs.version || '0.0.4' }}_linux_amd64.tar.gz
          tar -xvf terraform-cleaner_${{ github.event.inputs.version || '0.0.4' }}_linux_amd64.tar.gz
      - name: Run Terraform Cleaner
        id: terraform-cleaner
        run: |
          mv terraform-cleaner /usr/local/bin
          terraform-cleaner
          cleaner_output=$(terraform-cleaner 2>&1)
          echo "::set-output name=cleaner-output::$cleaner_output"
      - name: Get PR number
        id: PR
        run: echo "Pull Request number is ${{ github.event.pull_request.number }}"
        
      - name: Comment on PR
        uses: actions/github-script@v5.0.0
        
        env: 
          github-token: ${{ secrets.GH_PAT }}
        with:
         script: |
           github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "${{ env.cleaner_output }}"
            })




 
