name: Terraform Variable Cleanups

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tf-vars-cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Terraform Cleaner
        run: |
          VERSION="${{ github.event.inputs.version }}"
          wget "https://github.com/sylwit/terraform-cleaner/releases/download/v${{ github.event.inputs.version || '0.0.4' }}/terraform-cleaner_${{ github.event.inputs.version || '0.0.4' }}_linux_amd64.tar.gz"
          tar -xvf "terraform-cleaner_${{ github.event.inputs.version || '0.0.4' }}_linux_amd64.tar.gz"

      - name: Run Terraform Cleaner
        id: terraform-cleaner
        run: |
          mv terraform-cleaner /usr/local/bin
          terraform-cleaner
          cleaner_output=$(terraform-cleaner 2>&1)
          echo "::set-output name=cleaner-output::$cleaner_output"

      - name: Display Cleaner Output
        run: echo "Cleaner Output:${{ steps.terraform-cleaner.outputs.cleaner-output }}"

      - name: Debugging
        run: |
          echo "Cleaner Output Length: ${#cleaner_output}"
          echo "Cleaner Output: $cleaner_output"
          ls -l /usr/local/bin

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Terraform Variable Cleanups"
          title: "Terraform Variable Cleanups"
          body: ${{ env.cleaner_output }}
          branch: pull-request-comment
